// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO9zO-oKSMvwShwrR_IVRMo5fGPElx4eA',
    appId: '1:385849229795:web:6a7e9434e3ec59e96aa0d6',
    messagingSenderId: '385849229795',
    projectId: 'budget-app-49646',
    authDomain: 'budget-app-49646.firebaseapp.com',
    storageBucket: 'budget-app-49646.firebasestorage.app',
    measurementId: 'G-EXZ62336YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_G_wNodNUh0bBNfzl9hra0jBHo8_hQM8',
    appId: '1:385849229795:android:0fca81f2054dcdf26aa0d6',
    messagingSenderId: '385849229795',
    projectId: 'budget-app-49646',
    storageBucket: 'budget-app-49646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmUmy8ERvFNb9cu82LYbOTgnKcujqwNV4',
    appId: '1:385849229795:ios:369795a23a557ecc6aa0d6',
    messagingSenderId: '385849229795',
    projectId: 'budget-app-49646',
    storageBucket: 'budget-app-49646.firebasestorage.app',
    iosBundleId: 'com.example.personalBudgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmUmy8ERvFNb9cu82LYbOTgnKcujqwNV4',
    appId: '1:385849229795:ios:369795a23a557ecc6aa0d6',
    messagingSenderId: '385849229795',
    projectId: 'budget-app-49646',
    storageBucket: 'budget-app-49646.firebasestorage.app',
    iosBundleId: 'com.example.personalBudgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO9zO-oKSMvwShwrR_IVRMo5fGPElx4eA',
    appId: '1:385849229795:web:a781b34172bc4c5a6aa0d6',
    messagingSenderId: '385849229795',
    projectId: 'budget-app-49646',
    authDomain: 'budget-app-49646.firebaseapp.com',
    storageBucket: 'budget-app-49646.firebasestorage.app',
    measurementId: 'G-PFWH6NWBZC',
  );
}
